"""Export the authz subset of policy.json as Cedar policy text.

Why (see docs/Cedar-Evaluation.md): Cedar is the emerging industry dialect
for agent tool authorization (Bedrock AgentCore Policy, GA 2026-03, is
built on it). Aegis does NOT evaluate Cedar at decision time — the
enforcement path stays stdlib-only and fail-closed — but the control
function gets a faithful Cedar rendering of the authz subset, to:

  * run Cedar Analysis / the Cedar CLI on it at authoring time
    (prove non-contradiction, diff policy versions), and
  * port/audit Aegis policies in the dialect other tooling speaks.

What maps (and what doesn't):
  grants.tools / grants.binaries      -> one `permit` per granted entity
  grants.writable_paths               -> `permit ... when { context.path like ... }`
  tool_rules                          -> `forbid` per gated tool; a
                                         `block_if` REGEX is not expressible
                                         in Cedar (no regex) — exported as a
                                         comment, enforcement stays in Aegis
  rbac.principals                     -> per-principal permit/forbid
  mcp.manifests                       -> permit per declared server tool
  REQUIRE_APPROVAL                    -> Cedar has two effects only; rendered
                                         as `forbid` + @aegis_effect
                                         annotation (conservative: deny)

Content detectors, query rewriting, egress DLP, budgets, approvals are NOT
authz statements and are deliberately absent — Cedar decides, it never
scans or rewrites.

Run:  python -m aegis.cedar_export      (writes aegis/policy.cedar, self-checks)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

POLICY = Path(__file__).with_name("policy.json")
OUT = Path(__file__).with_name("policy.cedar")

_HEADER = """\
// GENERATED by `python -m aegis.cedar_export` from policy.json — do not edit.
// Authz subset only — detectors/proxies/budgets remain in the Aegis engine.
// Cedar semantics match the engine: default-deny (no permit => deny),
// forbid overrides permit.
"""


def _ann(rule_id: str, extra: dict | None = None) -> str:
    lines = [f'@id("{rule_id}")']
    for k, v in (extra or {}).items():
        lines.append(f'@{k}("{v}")')
    return "\n".join(lines)


def _permit(rule_id: str, action: str, resource: str, when: str | None = None,
            principal: str = "principal", extra: dict | None = None) -> str:
    body = (f"{_ann(rule_id, extra)}\n"
            f"permit (\n  {principal},\n"
            f"  action == Aegis::Action::\"{action}\",\n"
            f"  {resource}\n)")
    if when:
        body += f"\nwhen {{ {when} }}"
    return body + ";\n"


def _forbid(rule_id: str, tool: str, extra: dict | None = None,
            comment: str = "") -> str:
    out = ""
    if comment:
        out += f"// {comment}\n"
    out += (f"{_ann(rule_id, extra)}\n"
            f"forbid (\n  principal,\n"
            f"  action == Aegis::Action::\"call_tool\",\n"
            f"  resource == Aegis::Tool::\"{tool}\"\n);\n")
    return out


def _norm(p: str) -> str:
    return p.replace("\\", "/").rstrip("/").lstrip("./")


def to_cedar(policy: dict) -> str:
    parts: list[str] = [_HEADER]

    grants = policy.get("grants", {})
    if grants:
        parts.append("// --- grants (default-deny capability surface) ---\n")
        for t in grants.get("tools", []):
            parts.append(_permit(f"GRANT-TOOL-{t}", "use_tool",
                                 f'resource == Aegis::Tool::"{t}"'))
        for b in grants.get("binaries", []):
            parts.append(_permit(f"GRANT-BIN-{b}", "run_binary",
                                 f'resource == Aegis::Binary::"{b}"'))
        clauses = []
        for p in (_norm(x) for x in grants.get("writable_paths", [])):
            clauses.append(f'context.path == "{p}" || context.path like "{p}/*"')
        if clauses:
            parts.append(_permit("GRANT-WRITABLE-PATHS", "write_path", "resource",
                                 when=" ||\n       ".join(clauses)))

    rules = policy.get("tool_rules", {}).get("rules", {})
    if rules:
        parts.append("// --- tool_rules (named-tool gates) ---\n")
        for tool, r in rules.items():
            eff = r.get("effect", "block")
            extra = {"aegis_effect": eff}
            comment = ""
            if r.get("block_if"):
                comment = (f"NOT EXPRESSIBLE IN CEDAR: conditional on args regex "
                           f"/{r['block_if']}/ — enforced by the Aegis tool_rules "
                           f"pack; rendered here as unconditional {eff}.")
            parts.append(_forbid(f"TOOL-RULE-{tool}", tool, extra=extra,
                                 comment=comment))

    rbac = policy.get("rbac", {}).get("principals", {})
    if rbac:
        parts.append("// --- rbac (per-principal tool authorization) ---\n")
        for principal, row in rbac.items():
            pr = ("principal" if principal == "*"
                  else f'principal == Aegis::Agent::"{principal}"')
            for t in row.get("allow_tools", []) or []:
                parts.append(_permit(f"RBAC-{principal}-{t}", "use_tool",
                                     f'resource == Aegis::Tool::"{t}"',
                                     principal=pr))
            for t in row.get("deny_tools", []) or []:
                parts.append(
                    f'{_ann(f"RBAC-DENY-{principal}-{t}")}\n'
                    f"forbid (\n  {pr},\n"
                    f'  action == Aegis::Action::"use_tool",\n'
                    f'  resource == Aegis::Tool::"{t}"\n);\n')

    manifests = policy.get("mcp", {}).get("manifests", {})
    if manifests:
        parts.append("// --- mcp manifests (zero-privilege per server) ---\n")
        for server, m in manifests.items():
            for t in m.get("allow_tools", []):
                if t == "*":
                    parts.append(_permit(f"MCP-{server}-ALL", "call_mcp_tool",
                                         "resource",
                                         when=f'context.server == "{server}"'))
                else:
                    parts.append(_permit(f"MCP-{server}-{t}", "call_mcp_tool",
                                         f'resource == Aegis::McpTool::"{server}::{t}"'))

    return "\n".join(parts)


def run() -> int:
    policy = json.loads(POLICY.read_text(encoding="utf-8"))
    cedar = to_cedar(policy)
    OUT.write_text(cedar, encoding="utf-8")
    print("=== Cedar export (authz subset of policy.json) ===\n")
    print(f"  wrote {OUT.name}: {len(cedar.splitlines())} lines")

    checks: list[tuple[str, bool]] = []
    grants = policy.get("grants", {})
    n_permits = cedar.count("permit (")
    n_expected = (len(grants.get("tools", [])) + len(grants.get("binaries", []))
                  + (1 if grants.get("writable_paths") else 0))
    for server, m in policy.get("mcp", {}).get("manifests", {}).items():
        n_expected += len(m.get("allow_tools", []))
    for row in policy.get("rbac", {}).get("principals", {}).values():
        n_expected += len(row.get("allow_tools", []) or [])
    checks.append(("one permit per granted capability", n_permits == n_expected))
    checks.append(("every granted tool appears",
                   all(f'Aegis::Tool::"{t}"' in cedar for t in grants.get("tools", []))))
    checks.append(("every granted binary appears",
                   all(f'Aegis::Binary::"{b}"' in cedar for b in grants.get("binaries", []))))
    checks.append(("writable paths render as like-patterns",
                   all(f'like "{_norm(p)}/*"' in cedar
                       for p in grants.get("writable_paths", []))))
    checks.append(("balanced parens/braces",
                   cedar.count("(") == cedar.count(")")
                   and cedar.count("{") == cedar.count("}")))
    checks.append(("every statement terminated", cedar.count("permit (")
                   + cedar.count("forbid (") == cedar.count(";")))
    checks.append(("inexpressible regex gates are flagged, not dropped",
                   ("NOT EXPRESSIBLE" in cedar)
                   == any(r.get("block_if")
                          for r in policy.get("tool_rules", {}).get("rules", {}).values())))
    checks.append(("export is deterministic", to_cedar(policy) == cedar))

    for name, ok in checks:
        print(f"  {'PASS' if ok else 'FAIL'}  {name}")
    failed = [n for n, ok in checks if not ok]
    print(f"\n{'PASS' if not failed else 'FAIL'} — {len(checks) - len(failed)}/{len(checks)} checks")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(run())
